name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    name: ✅ Validate project
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: ⬇️ Checkout project
        uses: actions/checkout@v3

      - name: 🟢 Setup NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: 📥 Install dependencies
        run: npm ci

      - name: 🖍️ Check types
        run: npm run check:types

      - name: 💅 Check format
        run: npm run check:format

      - name: 📑 Check lint
        run: npm run check:lint

      - name: 🌐 Check html
        run: npm run check:html

      - name: 💄 Check scss
        run: npm run check:scss

      - name: 🔡 Check i18n
        run: npm run check:i18n

      - name: 🔤 Check spelling
        run: npm run check:spelling

  test:
    name: 🧑‍🔬 Test project
    runs-on: ubuntu-latest
    needs: validate
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: ⬇️ Checkout project
        uses: actions/checkout@v3

      - name: 🟢 Setup NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: 📥 Install dependencies
        run: npm ci

      - name: 🧪 Run the tests
        run: npm run test:coverage

  build:
    name: 🧰 Build project
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: ⬇️ Checkout project
        uses: actions/checkout@v3

      - name: 🟢 Setup NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: 📥 Install dependencies
        run: npm ci

      - name: ⚒️ Build project in SSR mode
        run: npm run build:ssr:prod
